export DF_BASE_PATH=~/.dotfiles
#export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home"
#export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home"

source $DF_BASE_PATH/aliases.sh
source $DF_BASE_PATH/autojump.sh
source $DF_BASE_PATH/bash_colors.sh
source $DF_BASE_PATH/bash_completion.sh
source $DF_BASE_PATH/bash_path.sh
source $DF_BASE_PATH/bash_prompt.sh
source $DF_BASE_PATH/control.sh
source $DF_BASE_PATH/docker.sh
source $DF_BASE_PATH/editor.sh
source $DF_BASE_PATH/git.sh
source $DF_BASE_PATH/heroku.sh
source $DF_BASE_PATH/node.sh
source $DF_BASE_PATH/rails.sh
source $DF_BASE_PATH/ruby.sh
source $DF_BASE_PATH/xquartz.sh
